from setuptools import setup, find_packages

setup(
    name="code-teaching-video-agent",
    version="1.0.0",
    description="AI-powered code teaching video generator",
    author="Code Teaching Video Agent Contributors",
    author_email="contact@example.com",
    url="https://github.com/[username]/code-teaching-video-agent",
    python_requires=">=3.8",
    packages=find_packages(),
    install_requires=[
        "edge-tts>=6.1.0",
        "manim>=0.18.0",
        "ffmpeg-python>=0.2.0",
        "tree-sitter>=0.20.0",
        "pygments>=2.15.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "moviepy>=1.0.3",
        "imageio>=2.31.0",
        "tqdm>=4.65.0",
        "click>=8.1.0",
        "pyyaml>=6.0",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Education",
        "Topic :: Multimedia :: Video",
        "Topic :: Scientific/Engineering :: Visualization",
    ],
    keywords="code teaching video algorithm visualization manim tts",
)